controller_list:
  - name: fake_examplerobot_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - base_link__link_01
      - link_01__link_02
      - link_02__link_03
      - link_03__link_04
      - link_04__link_05
      - link_05__link_06
  - name: fake_examplerobot_end_effector_controller
    type: $(arg fake_execution_type)
    joints:
      []
initial:  # Define initial robot poses per group
  - group: examplerobot_arm
    pose: pose_00